version: '3'

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
  web:
    build: .
    command: gunicorn --bind :8000 --workers 3 --threads 2 spaceiz_chat.wsgi:application
    volumes:
      - .:/spaceiz_chat
    ports:
      - "8000:8000"

  migration:
    build: .
    command: python manage.py migrate --noinput
    volumes:
      - .:/spaceiz_chat

  channels:
    build: .
    command: daphne -b 0.0.0.0 -p 8001 spaceiz_chat.asgi:application
    volumes:
      - .:/spaceiz_chat
    ports:
      - "8001:8001"
    links:
      - redis